Page({
    data:{
        birthInfo:[
            {
                id:1,
                title:'姓名',
                content:'张晓'
            },
            {
                id:2,
                title:'性别',
                content:'女'
            },
            {
                id:3,
                title:'生日',
                content:'阴历|1962年06月12日'
            },
            {
                id:4,
                title:'手机',
                content:'150****4376'
            },
            {
                id:5,
                title:'关系',
                content:'母亲'
            },
            {
                id:6,
                title:'家乡',
                content:''
            },
            {
                id:7,
                title:'地址',
                content:''
            },
            {
                id:8,
                title:'公司',
                content:''
            },
            {
                id:9,
                title:'情感状况',
                content:'单身'
            },
            {
                id:10,
                title:'生日提醒',
                content:'提前2天提醒'
            },
            {
                id:11,
                title:'备注',
                content:''
            },
        ]
    },
    backToList:function (e) {
        var url = e.currentTarget.dataset.id;
        wx.navigateTo({
            url:url
        })
    }
})